apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: influxdb-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: influxdb-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "InfluxDB"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: influxdb-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: influxdb-influxdb
          servicePort: 8086
